version: '3.5'


services:

  # D3 common registration service
  d3-registration:
    image: docker.soramitsu.co.jp/soranet/notary-registration:${TAG-master}
    container_name: d3-registration
    restart: on-failure
    ports:
      - 8085:8085
      - 7075:7075
    environment:
      - PROFILE
    networks:
      - d3-network

  d3-exchanger:
    image: docker.soramitsu.co.jp/soranet/exchanger:${TAG-master}
    container_name: d3-exchanger
    restart: on-failure
    environment:
      - PROFILE
    networks:
      - d3-network

  # d3-changelog:
  #   image: docker.soramitsu.co.jp/soranet/changelog-endpoint:latest
  #   container_name: d3-changelog
  #   restart: on-failure
  #   ports:
  #     - 9999:9999
  #   networks:
  #     - d3-network

  d3-notifications:
    image: docker.soramitsu.co.jp/soranet/notifications:${TAG-master}
    container_name: d3-notifications
    restart: on-failure
    networks:
      - d3-network

networks:
  d3-network:
